### ISSUE TITLE
严格模式下出错

### ISSUE THREAD

**Issue by lonelyclick** [BaiduFE/BaiduTemplate#37]
用了use strict 之后，好像eval的this只想错了，有解决的办法么？

**Comment by yanhaijing** [comment]
同问，这个问题什么时候能修好？

**Comment by yanhaijing** [comment]
这个问题什么时候能够修好，用了babel后 全部都是严格模式了

**Comment by yanhaijing** [comment]
这个问题直接关闭了？？？？？？？？？？？？？？？？？？？？？？？？
